# Generated by Django 4.2.27 on 2026-02-03 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
        ('halaqat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_start', models.PositiveIntegerField(verbose_name='آية البداية')),
                ('ayah_end', models.PositiveIntegerField(verbose_name='آية النهاية')),
                ('recitation_type', models.CharField(choices=[('new', 'حفظ جديد'), ('review', 'مراجعة'), ('tilawa', 'تلاوة')], default='new', max_length=20, verbose_name='نوع التسميع')),
                ('grade', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة')),
                ('grade_level', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], max_length=20, verbose_name='مستوى التقييم')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأخطاء')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='المدة بالدقائق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الشيخ')),
                ('sheikh_feedback', models.TextField(blank=True, verbose_name='تعليق الشيخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_records', to='halaqat.session', verbose_name='الجلسة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_records', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('surah_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_ends', to='quran.surah', verbose_name='سورة النهاية')),
                ('surah_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation_starts', to='quran.surah', verbose_name='سورة البداية')),
            ],
            options={
                'verbose_name': 'سجل تسميع',
                'verbose_name_plural': 'سجلات التسميع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecitationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah', models.PositiveIntegerField(verbose_name='رقم الآية')),
                ('word_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب الكلمة')),
                ('word_text', models.CharField(blank=True, max_length=100, verbose_name='نص الكلمة')),
                ('error_type', models.CharField(choices=[('tajweed', 'خطأ تجويد'), ('tashkeel', 'خطأ تشكيل'), ('forget', 'نسيان'), ('addition', 'إضافة'), ('replacement', 'إبدال'), ('hesitation', 'تردد'), ('pronunciation', 'نطق')], max_length=20, verbose_name='نوع الخطأ')),
                ('severity', models.CharField(choices=[('minor', 'بسيط'), ('major', 'جسيم'), ('critical', 'خطير')], default='minor', max_length=20, verbose_name='شدة الخطأ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='recitation.recitationrecord', verbose_name='سجل التسميع')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'خطأ تسميع',
                'verbose_name_plural': 'أخطاء التسميع',
                'ordering': ['surah', 'ayah', 'word_index'],
            },
        ),
        migrations.CreateModel(
            name='MemorizationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_from', models.PositiveIntegerField(default=1, verbose_name='من آية')),
                ('ayah_to', models.PositiveIntegerField(verbose_name='إلى آية')),
                ('is_memorized', models.BooleanField(default=False, verbose_name='تم الحفظ')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر مراجعة')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='عدد المراجعات')),
                ('average_grade', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='متوسط الدرجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'تقدم حفظ',
                'verbose_name_plural': 'تقدم الحفظ',
                'unique_together': {('student', 'surah', 'ayah_from', 'ayah_to')},
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('target_new_lines', models.PositiveIntegerField(default=5, verbose_name='أسطر الحفظ المستهدفة')),
                ('actual_new_lines', models.PositiveIntegerField(default=0, verbose_name='أسطر الحفظ الفعلية')),
                ('target_review_pages', models.PositiveIntegerField(default=2, verbose_name='صفحات المراجعة المستهدفة')),
                ('actual_review_pages', models.PositiveIntegerField(default=0, verbose_name='صفحات المراجعة الفعلية')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='تم تحقيق الهدف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'هدف يومي',
                'verbose_name_plural': 'الأهداف اليومية',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
