# Generated by Django 4.2.28 on 2026-02-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التخطيط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_system', models.BooleanField(default=False, verbose_name='نظامي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تخطيط لوحة التحكم',
                'verbose_name_plural': 'تخطيطات لوحة التحكم',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الأداة')),
                ('widget_type', models.CharField(choices=[('stats_card', 'بطاقة إحصائيات'), ('chart_line', 'رسم خطي'), ('chart_bar', 'رسم أعمدة'), ('chart_pie', 'رسم دائري'), ('chart_doughnut', 'رسم دائري مجوف'), ('table', 'جدول'), ('list', 'قائمة'), ('calendar', 'تقويم'), ('progress', 'شريط تقدم'), ('recent_activity', 'النشاط الأخير')], max_length=20, verbose_name='نوع الأداة')),
                ('data_source', models.CharField(choices=[('users', 'المستخدمين'), ('students', 'الطلاب'), ('sheikhs', 'المشايخ'), ('halaqat', 'الحلقات'), ('sessions', 'الجلسات'), ('recitations', 'التسميعات'), ('attendance', 'الحضور'), ('points', 'النقاط'), ('badges', 'الأوسمة'), ('certificates', 'الشهادات'), ('custom', 'مخصص')], max_length=20, verbose_name='مصدر البيانات')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='العنوان الفرعي')),
                ('icon', models.CharField(default='fa-chart-line', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(choices=[('primary', 'أزرق'), ('secondary', 'رمادي'), ('success', 'أخضر'), ('danger', 'أحمر'), ('warning', 'أصفر'), ('info', 'سماوي'), ('dark', 'داكن')], default='primary', max_length=20, verbose_name='اللون')),
                ('width', models.PositiveIntegerField(default=4, help_text='من 1 إلى 12', verbose_name='العرض (أعمدة)')),
                ('height', models.PositiveIntegerField(blank=True, default=300, null=True, verbose_name='الارتفاع (بكسل)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, verbose_name='شروط التصفية')),
                ('date_range', models.CharField(choices=[('today', 'اليوم'), ('week', 'هذا الأسبوع'), ('month', 'هذا الشهر'), ('quarter', 'هذا الربع'), ('year', 'هذا العام'), ('all', 'الكل')], default='all', max_length=20, verbose_name='نطاق التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'أداة لوحة التحكم',
                'verbose_name_plural': 'أدوات لوحة التحكم',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('auto', 'تلقائي')], default='light', max_length=20, verbose_name='السمة')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='القائمة الجانبية مطوية')),
                ('items_per_page', models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100'), (200, '200')], default=25, verbose_name='عناصر لكل صفحة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='إشعارات المتصفح')),
                ('hidden_columns', models.JSONField(blank=True, default=dict, verbose_name='الأعمدة المخفية')),
                ('table_ordering', models.JSONField(blank=True, default=dict, verbose_name='ترتيب الجداول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات لوحة التحكم',
                'verbose_name_plural': 'إعدادات لوحة التحكم',
            },
        ),
        migrations.CreateModel(
            name='DashboardLayoutWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض مخصص')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب مخصص')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات مخصصة')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardlayout')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget')),
            ],
            options={
                'verbose_name': 'أداة في التخطيط',
                'verbose_name_plural': 'أدوات في التخطيط',
                'ordering': ['custom_order'],
                'unique_together': {('layout', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='widgets',
            field=models.ManyToManyField(related_name='layouts', through='dashboard.DashboardLayoutWidget', to='dashboard.dashboardwidget', verbose_name='الأدوات'),
        ),
        migrations.CreateModel(
            name='BulkAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإجراء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('action_type', models.CharField(choices=[('delete', 'حذف'), ('update', 'تحديث حقول'), ('export', 'تصدير'), ('notify', 'إرسال إشعار'), ('change_status', 'تغيير الحالة')], max_length=50, verbose_name='نوع الإجراء')),
                ('field_updates', models.JSONField(blank=True, default=dict, verbose_name='الحقول للتحديث')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, verbose_name='شروط التصفية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bulk_actions', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'إجراء جماعي',
                'verbose_name_plural': 'الإجراءات الجماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('other', 'آخر')], max_length=20, verbose_name='نوع الإجراء')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='تمثيل الكائن')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='وكيل المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل إجراء إداري',
                'verbose_name_plural': 'سجل الإجراءات الإدارية',
                'ordering': ['-created_at'],
            },
        ),
    ]
