# Generated by Django 4.2.28 on 2026-02-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session', 'جلسة'), ('recitation', 'تسميع'), ('enrollment', 'تسجيل'), ('certificate', 'شهادة'), ('badge', 'وسام'), ('points', 'نقاط'), ('system', 'نظام'), ('reminder', 'تذكير'), ('alert', 'تنبيه')], default='system', max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='الرابط')),
                ('link_text', models.CharField(default='عرض', max_length=100, verbose_name='نص الرابط')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('shown_in_ui', models.BooleanField(default=False, verbose_name='ظهر في الواجهة')),
                ('email_sent', models.BooleanField(default=False, verbose_name='أُرسل بريد')),
                ('push_sent', models.BooleanField(default=False, verbose_name='أُرسل Push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('direct', 'رسالة مباشرة'), ('broadcast', 'رسالة جماعية'), ('system', 'رسالة نظام'), ('alert', 'تنبيه')], default='direct', max_length=20, verbose_name='نوع الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_draft', models.BooleanField(default=False, verbose_name='مسودة')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='تم القراءة بواسطة')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلمون')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('students', 'طلاب'), ('sheikhs', 'مشايخ'), ('halaqat', 'حلقات')], max_length=20, verbose_name='نوع الاستيراد')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_path', models.FileField(upload_to='imports/', verbose_name='الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('partial', 'مكتمل جزئياً'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('create_accounts', models.BooleanField(default=True, verbose_name='إنشاء حسابات')),
                ('auto_distribute', models.BooleanField(default=False, verbose_name='توزيع تلقائي')),
                ('distribution_count', models.PositiveIntegerField(default=10, help_text='عدد الحلقات التي سيتم توزيع الطلاب عليها', verbose_name='عدد الحلقات للتوزيع')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='النجاح')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='الفشل')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='التخطي')),
                ('errors_log', models.JSONField(blank=True, default=list, verbose_name='سجل الأخطاء')),
                ('created_users', models.JSONField(blank=True, default=list, verbose_name='المستخدمون المنشأون')),
                ('created_halaqat', models.JSONField(blank=True, default=list, verbose_name='الحلقات المنشأة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'عملية استيراد Excel',
                'verbose_name_plural': 'عمليات استيراد Excel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('error', 'خطأ'), ('success', 'نجاح')], default='info', max_length=20, verbose_name='نوع التنبيه')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='مثل: ["admin", "sheikh"]', verbose_name='الأدوار المستهدفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_once', models.BooleanField(default=False, verbose_name='إظهار مرة واحدة')),
                ('dismissible', models.BooleanField(default=True, verbose_name='قابل للإغلاق')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('dismissed_by', models.ManyToManyField(blank=True, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL, verbose_name='تم إغلاقه بواسطة')),
                ('target_users', models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المستهدفون')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
    ]
