# Generated by Django 4.2.27 on 2026-02-03 17:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'مدير'), ('sheikh', 'شيخ'), ('student', 'طالب'), ('parent', 'ولي أمر')], default='student', max_length=10, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='عضو نشط')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_surah', models.PositiveIntegerField(default=1, verbose_name='السورة الحالية')),
                ('current_ayah', models.PositiveIntegerField(default=1, verbose_name='الآية الحالية')),
                ('total_memorized_pages', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفحات المحفوظة')),
                ('total_memorized_juz', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأجزاء المحفوظة')),
                ('memorization_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الحفظ')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإتمام المستهدف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='ولي الأمر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف طالب',
                'verbose_name_plural': 'ملفات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='SheikhProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('hifz', 'حفظ'), ('tajweed', 'تجويد'), ('qiraat', 'قراءات'), ('ijazah', 'إجازة')], default='hifz', max_length=20, verbose_name='التخصص')),
                ('ijazah_info', models.TextField(blank=True, verbose_name='معلومات الإجازة')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('max_students', models.PositiveIntegerField(default=20, verbose_name='الحد الأقصى للطلاب')),
                ('available_days', models.CharField(blank=True, max_length=100, verbose_name='أيام التوفر')),
                ('available_times', models.TextField(blank=True, verbose_name='أوقات التوفر')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الأجر بالساعة')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='التقييم')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='إجمالي الجلسات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheikh_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شيخ',
                'verbose_name_plural': 'ملفات المشايخ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session', 'جلسة'), ('grade', 'درجة'), ('badge', 'وسام'), ('system', 'نظام'), ('reminder', 'تذكير')], default='system', max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='الإجراء')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
            },
        ),
    ]
