# Generated by Django 4.2.28 on 2026-02-05 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halaqat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('template_image', models.ImageField(help_text='ارفع صورة خلفية الشهادة (مثلاً: JPG, PNG)', upload_to='certificates/templates/', verbose_name='صورة القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_font_size', models.PositiveIntegerField(default=48, verbose_name='حجم خط الاسم')),
                ('name_font_color', models.CharField(default='#000000', max_length=20, verbose_name='لون خط الاسم')),
                ('name_position_x', models.PositiveIntegerField(default=540, verbose_name='موقع الاسم X')),
                ('name_position_y', models.PositiveIntegerField(default=400, verbose_name='موقع الاسم Y')),
                ('name_font_family', models.CharField(blank=True, default='Arial', max_length=100, verbose_name='خط الاسم')),
                ('degree_font_size', models.PositiveIntegerField(default=36, verbose_name='حجم خط الدرجة')),
                ('degree_font_color', models.CharField(default='#333333', max_length=20, verbose_name='لون خط الدرجة')),
                ('degree_position_x', models.PositiveIntegerField(default=540, verbose_name='موقع الدرجة X')),
                ('degree_position_y', models.PositiveIntegerField(default=500, verbose_name='موقع الدرجة Y')),
                ('degree_font_family', models.CharField(blank=True, default='Arial', max_length=100, verbose_name='خط الدرجة')),
                ('date_font_size', models.PositiveIntegerField(default=24, verbose_name='حجم خط التاريخ')),
                ('date_font_color', models.CharField(default='#666666', max_length=20, verbose_name='لون خط التاريخ')),
                ('date_position_x', models.PositiveIntegerField(default=540, verbose_name='موقع التاريخ X')),
                ('date_position_y', models.PositiveIntegerField(default=600, verbose_name='موقع التاريخ Y')),
                ('date_font_family', models.CharField(blank=True, default='Arial', max_length=100, verbose_name='خط التاريخ')),
                ('default_title', models.CharField(blank=True, default='شهادة إتمام', max_length=200, verbose_name='عنوان الشهادة الافتراضي')),
                ('default_description', models.TextField(blank=True, default='تم منح هذه الشهادة تقديراً لإتمام', verbose_name='وصف الإنجاز الافتراضي')),
            ],
            options={
                'verbose_name': 'قالب شهادة',
                'verbose_name_plural': 'قوالب الشهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('custom', 'مخصص')], default='monthly', max_length=20, verbose_name='فترة التقرير')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='عدد الجلسات')),
                ('total_recitations', models.PositiveIntegerField(default=0, verbose_name='عدد التسميعات')),
                ('total_pages_memorized', models.PositiveIntegerField(default=0, verbose_name='الصفحات المحفوظة')),
                ('total_pages_reviewed', models.PositiveIntegerField(default=0, verbose_name='الصفحات المراجعة')),
                ('average_grade', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='متوسط الدرجة')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الحضور')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأخطاء')),
                ('tajweed_errors', models.PositiveIntegerField(default=0, verbose_name='أخطاء التجويد')),
                ('memorization_errors', models.PositiveIntegerField(default=0, verbose_name='أخطاء الحفظ')),
                ('general_evaluation', models.TextField(blank=True, verbose_name='التقييم العام')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('detailed_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات التفصيلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقرير طالب',
                'verbose_name_plural': 'تقارير الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('custom_name', models.CharField(blank=True, help_text='اتركه فارغاً لاستخدام اسم الطلبة الافتراضي', max_length=200, verbose_name='الاسم على الشهادة')),
                ('degree_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الدرجة/الإنجاز')),
                ('degree_description', models.TextField(blank=True, verbose_name='وصف الإنجاز')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'صادرة'), ('revoked', 'ملغاة')], default='issued', max_length=20, verbose_name='الحالة')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='certificates/generated/', verbose_name='ملف الشهادة')),
                ('name_position_x_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='X الاسم (تجاوز)')),
                ('name_position_y_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y الاسم (تجاوز)')),
                ('degree_position_x_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='X الدرجة (تجاوز)')),
                ('degree_position_y_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y الدرجة (تجاوز)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='reports.certificatetemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkCertificateGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=200, verbose_name='عنوان الدرجة')),
                ('degree_description', models.TextField(blank=True, verbose_name='وصف الإنجاز')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('min_grade', models.DecimalField(decimal_places=1, default=0, help_text='توليد شهادات للطلاب بدرجة أعلى من هذا', max_digits=4, verbose_name='الحد الأدنى للدرجة')),
                ('min_attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='نسبة الحضور المطلوبة', max_digits=5, verbose_name='الحد الأدنى للحضور')),
                ('generated_count', models.PositiveIntegerField(default=0, verbose_name='عدد الشهادات المولدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_generations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_certificates', to='halaqat.halaqa', verbose_name='الحلقة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_generations', to='reports.certificatetemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'توليد شهادات بالجملة',
                'verbose_name_plural': 'توليد الشهادات بالجملة',
                'ordering': ['-created_at'],
            },
        ),
    ]
