# Generated by Django 4.2.27 on 2026-02-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم الصفحة')),
                ('juz', models.PositiveIntegerField(verbose_name='الجزء')),
                ('hizb', models.PositiveIntegerField(verbose_name='الحزب')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم السورة')),
                ('name_arabic', models.CharField(max_length=50, verbose_name='اسم السورة بالعربية')),
                ('name_english', models.CharField(max_length=50, verbose_name='اسم السورة بالإنجليزية')),
                ('name_transliteration', models.CharField(blank=True, max_length=50, verbose_name='اسم السورة بالحروف اللاتينية')),
                ('total_ayat', models.PositiveIntegerField(verbose_name='عدد الآيات')),
                ('revelation_type', models.CharField(choices=[('meccan', 'مكية'), ('medinan', 'مدنية')], max_length=10, verbose_name='نوع النزول')),
                ('revelation_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب النزول')),
                ('page_start', models.PositiveIntegerField(verbose_name='صفحة البداية')),
                ('page_end', models.PositiveIntegerField(verbose_name='صفحة النهاية')),
                ('juz_start', models.PositiveIntegerField(default=1, verbose_name='الجزء')),
            ],
            options={
                'verbose_name': 'سورة',
                'verbose_name_plural': 'السور',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم الجزء')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الجزء')),
                ('start_ayah', models.PositiveIntegerField(verbose_name='آية البداية')),
                ('end_ayah', models.PositiveIntegerField(verbose_name='آية النهاية')),
                ('end_surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz_ends', to='quran.surah', verbose_name='سورة النهاية')),
                ('start_surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz_starts', to='quran.surah', verbose_name='سورة البداية')),
            ],
            options={
                'verbose_name': 'جزء',
                'verbose_name_plural': 'الأجزاء',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Hizb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم الحزب')),
                ('start_ayah', models.PositiveIntegerField(verbose_name='آية البداية')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahzab', to='quran.juz', verbose_name='الجزء')),
                ('start_surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizb_starts', to='quran.surah', verbose_name='سورة البداية')),
            ],
            options={
                'verbose_name': 'حزب',
                'verbose_name_plural': 'الأحزاب',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم الآية')),
                ('number_in_quran', models.PositiveIntegerField(default=0, verbose_name='الرقم في القرآن')),
                ('text_uthmani', models.TextField(verbose_name='النص بالرسم العثماني')),
                ('text_simple', models.TextField(blank=True, verbose_name='النص المبسط')),
                ('page', models.PositiveIntegerField(verbose_name='الصفحة')),
                ('juz', models.PositiveIntegerField(verbose_name='الجزء')),
                ('hizb', models.PositiveIntegerField(verbose_name='الحزب')),
                ('quarter', models.PositiveIntegerField(default=1, verbose_name='الربع')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayat', to='quran.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'آية',
                'verbose_name_plural': 'الآيات',
                'ordering': ['surah', 'number'],
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
