# Generated by Django 4.2.27 on 2026-02-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المسار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('course_type', models.CharField(choices=[('hifz', 'حفظ'), ('muraja', 'مراجعة'), ('tajweed', 'تجويد'), ('tilawa', 'تلاوة'), ('ijazah', 'إجازة')], default='hifz', max_length=20, verbose_name='نوع المسار')),
                ('duration_months', models.PositiveIntegerField(default=12, verbose_name='المدة بالأشهر')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'مسار',
                'verbose_name_plural': 'المسارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحلقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للطلاب')),
                ('schedule_days', models.CharField(blank=True, max_length=100, verbose_name='أيام الحلقة')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحلقة')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدة الجلسة بالدقائق')),
                ('meet_link', models.URLField(blank=True, verbose_name='رابط Google Meet')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('paused', 'متوقفة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_private', models.BooleanField(default=False, verbose_name='حلقة خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqat', to='halaqat.course', verbose_name='المسار')),
                ('sheikh', models.ForeignKey(limit_choices_to={'user_type': 'sheikh'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_halaqat', to=settings.AUTH_USER_MODEL, verbose_name='الشيخ')),
            ],
            options={
                'verbose_name': 'حلقة',
                'verbose_name_plural': 'الحلقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء الفعلي')),
                ('meet_link', models.URLField(blank=True, verbose_name='رابط الاجتماع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('in_progress', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('postponed', 'مؤجلة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='halaqat.halaqa', verbose_name='الحلقة')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HalaqaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('withdrawn', 'منسحب'), ('suspended', 'موقوف')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='halaqat.halaqa', verbose_name='الحلقة')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='halaqa_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل في حلقة',
                'verbose_name_plural': 'تسجيلات الحلقات',
                'ordering': ['-enrolled_date'],
                'unique_together': {('student', 'halaqa')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'معذور'), ('late', 'متأخر')], default='present', max_length=20, verbose_name='الحالة')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='halaqat.session', verbose_name='الجلسة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'سجل الحضور',
                'unique_together': {('student', 'session')},
            },
        ),
    ]
