# Generated by Django 4.2.28 on 2026-02-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halaqat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('content_type', models.CharField(choices=[('lesson', 'درس اليوم'), ('reminder', 'تذكير بالدرس'), ('morning_motivation', 'تحفيز صباحي'), ('evening_reflection', 'تأمل مسائي'), ('encouragement', 'رسائل تشجيعية'), ('awareness', 'رسائل توعوية'), ('announcement', 'إعلان عام')], max_length=30, verbose_name='نوع المحتوى')),
                ('title_template', models.CharField(max_length=200, verbose_name='عنوان القالب')),
                ('message_template', models.TextField(verbose_name='نص القالب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification_templates/', verbose_name='صورة')),
                ('link', models.URLField(blank=True, verbose_name='رابط')),
                ('available_variables', models.JSONField(default=list, help_text='متغيرات مثل: {student_name}, {lesson_title}, {surah_name}', verbose_name='المتغيرات المتاحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('endpoint_type', models.CharField(choices=[('primary', 'رئيسي'), ('secondary', 'ثانوي'), ('test', 'اختبار')], default='primary', max_length=20, verbose_name='نوع النقطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='مهلة الانتظار (ثانية)')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='الهيدرز المخصصة')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='عدد النجاحات')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='عدد الفشل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نقطة Webhook',
                'verbose_name_plural': 'نقاط Webhook',
                'ordering': ['endpoint_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content_type', models.CharField(choices=[('lesson', 'درس اليوم'), ('reminder', 'تذكير بالدرس'), ('morning_motivation', 'تحفيز صباحي'), ('evening_reflection', 'تأمل مسائي'), ('encouragement', 'رسائل تشجيعية'), ('awareness', 'رسائل توعوية'), ('announcement', 'إعلان عام')], max_length=30, verbose_name='نوع المحتوى')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scheduled_notifications/', verbose_name='صورة')),
                ('link', models.URLField(blank=True, verbose_name='رابط')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='تاريخ ووقت الإرسال')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('recurrence_type', models.CharField(choices=[('one_time', 'مرة واحدة'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('biweekly', 'مرتين في الأسبوع'), ('monthly', 'شهري'), ('custom', 'مخصص')], default='one_time', max_length=20, verbose_name='نوع التكرار')),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='للتكرار الأسبوعي: [0, 2, 4] للأحد، الثلاثاء، الخميس', verbose_name='أيام التكرار')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار')),
                ('target_type', models.CharField(choices=[('all_students', 'جميع الطلاب'), ('all_parents', 'جميع أولياء الأمور'), ('all_teachers', 'جميع المشايخ'), ('halaqa', 'حلقة محددة'), ('course', 'مقرر محدد'), ('specific_users', 'مستخدمين محددين')], default='all_students', max_length=20, verbose_name='نوع المستهدفين')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('sending', 'جاري الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='إجمالي المستلمين')),
                ('successful_sends', models.PositiveIntegerField(default=0, verbose_name='الإرسال الناجح')),
                ('failed_sends', models.PositiveIntegerField(default=0, verbose_name='الإرسال الفاشل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ns_created_scheduled_notifications', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.curriculumlesson', verbose_name='الدرس')),
                ('parent_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_notifications', to='notifications_system.schedulednotification', verbose_name='الإشعار الأصلي')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ns_sent_scheduled_notifications', to=settings.AUTH_USER_MODEL, verbose_name='أُرسل بواسطة')),
                ('tafseer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.tafseerlesson', verbose_name='درس التفسير')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum', verbose_name='المقرر المستهدف')),
                ('target_halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halaqat.halaqa', verbose_name='الحلقة المستهدفة')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_scheduled_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المستهدفون')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications_system.notificationtemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'إشعار مجدول',
                'verbose_name_plural': 'الإشعارات المجدولة',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField(verbose_name='رابط Webhook')),
                ('payload', models.JSONField(verbose_name='البيانات المرسلة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('success', 'نجاح'), ('failed', 'فشل'), ('retrying', 'إعادة محاولة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='رمز الاستجابة')),
                ('response_body', models.TextField(blank=True, verbose_name='نص الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='أول محاولة')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر محاولة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='notifications_system.schedulednotification', verbose_name='الإشعار')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatch_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'سجل إرسال',
                'verbose_name_plural': 'سجلات الإرسال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('updated', 'تعديل'), ('deleted', 'حذف'), ('sent', 'إرسال'), ('cancelled', 'إلغاء'), ('enabled', 'تفعيل'), ('disabled', 'تعطيل')], max_length=20, verbose_name='الإجراء')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='وكيل المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='notifications_system.schedulednotification', verbose_name='الإشعار')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='notificatio_status_d95c66_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['content_type', 'status'], name='notificatio_content_5adae8_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotification',
            index=models.Index(fields=['is_enabled', 'status'], name='notificatio_is_enab_1e483e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdispatchlog',
            index=models.Index(fields=['status', 'attempt_count'], name='notificatio_status_105db9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdispatchlog',
            index=models.Index(fields=['notification', 'status'], name='notificatio_notific_34b976_idx'),
        ),
    ]
