# Generated by Django 4.2.27 on 2026-02-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإنجاز')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('achievement_type', models.CharField(choices=[('surah_complete', 'إتمام سورة'), ('juz_complete', 'إتمام جزء'), ('hifz_complete', 'ختم القرآن'), ('sessions_count', 'عدد الجلسات'), ('perfect_grade', 'درجة كاملة'), ('streak_days', 'أيام مواظبة')], max_length=30, verbose_name='نوع الإنجاز')),
                ('icon', models.CharField(default='fa-trophy', max_length=50, verbose_name='أيقونة')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='النقاط المكافأة')),
                ('target_value', models.PositiveIntegerField(default=1, verbose_name='القيمة المستهدفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'الإنجازات',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوسام')),
                ('name_english', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fa-medal', max_length=50, verbose_name='أيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='صورة الوسام')),
                ('badge_type', models.CharField(choices=[('memorization', 'حفظ'), ('attendance', 'حضور'), ('achievement', 'إنجاز'), ('special', 'خاص'), ('streak', 'مواظبة')], default='achievement', max_length=20, verbose_name='نوع الوسام')),
                ('level', models.CharField(choices=[('bronze', 'برونزي'), ('silver', 'فضي'), ('gold', 'ذهبي'), ('platinum', 'بلاتيني'), ('diamond', 'ماسي')], default='bronze', max_length=20, verbose_name='مستوى الوسام')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='النقاط المكافأة')),
                ('criteria_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المعيار')),
                ('criteria_value', models.PositiveIntegerField(default=0, verbose_name='قيمة المعيار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وسام',
                'verbose_name_plural': 'الأوسمة',
                'ordering': ['badge_type', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='المواظبة الحالية')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='أطول مواظبة')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر نشاط')),
                ('total_active_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي أيام النشاط')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مواظبة',
                'verbose_name_plural': 'سجلات المواظبة',
            },
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('points_type', models.CharField(choices=[('recitation', 'تسميع'), ('attendance', 'حضور'), ('badge', 'وسام'), ('achievement', 'إنجاز'), ('bonus', 'مكافأة'), ('deduction', 'خصم'), ('streak', 'مواظبة')], default='recitation', max_length=20, verbose_name='نوع النقاط')),
                ('reason', models.CharField(max_length=200, verbose_name='السبب')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_logs', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل نقاط',
                'verbose_name_plural': 'سجلات النقاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('all_time', 'الكل')], max_length=20, verbose_name='نوع الفترة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'متصدر',
                'verbose_name_plural': 'لوحة المتصدرين',
                'ordering': ['-period_start', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحصول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge', verbose_name='الوسام')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'وسام طالب',
                'verbose_name_plural': 'أوسمة الطلاب',
                'ordering': ['-earned_date'],
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='التقدم')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieved_by', to='gamification.achievement', verbose_name='الإنجاز')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إنجاز طالب',
                'verbose_name_plural': 'إنجازات الطلاب',
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
